INSERT INTO COURSE VALUES (101,'JPA beginner friendly');
INSERT INTO COURSE VALUES (102,'Spring beginner friendly');
INSERT INTO COURSE VALUES (103,'SpringBoo beginner friendly');

INSERT INTO PASSPORT VALUES (403,'401LTF');
INSERT INTO PASSPORT VALUES (404,'402LTF');
INSERT INTO PASSPORT VALUES (405,'403LTF');

INSERT INTO STUDENT VALUES (201,'Tifa',403);
INSERT INTO STUDENT VALUES (202,'Cloud',404);
INSERT INTO STUDENT VALUES (203,'Sephiroth',405);

